package ruby.command.meta;

public enum CommandCategory {
    GENERAL,
    GUILD_STATISTICS,
    TEXT_CHANNEL_MANAGEMENT,
    VOICE_CHANNEL_MANAGEMENT,
    MEMBER_MANAGEMENT,
    GUILD_MANAGEMENT,
    BOT_MANAGEMENT
}
